{% set name = "radiospectra" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94840b28d38b6a811bec8e601a9bcf9d789e44fbeb3ebf173d303fcb38e7864a

build:
  number: 0
  script: python setup.py install --offline --no-git --single-version-externally-managed --record record.tx

requirements:
  host:
    - pip
    - python
    - sunpy
  run:
    - python
    - sunpy

test:
  imports:
    - radiospectra
    - radiospectra.sources
    - radiospectra.tests

about:
  home: http://sunpy.org
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: radio spectra capabilities for SunPy

extra:
  recipe-maintainers:
    - Cadair
    - nabobalis
